name: project_dev
on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing
  schedule:
    - cron: '0 12,24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.2
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Pytest testing
        run: pytest
      - name: Fetch data
        run: | 
          python src/data/fetch_data_air.py && \
          python src/data/process_data_air.py && \
          python src/data/fetch_data_weather.py && \
          python src/data/process_data_weather.py